apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-csi-rbd-provisioner
  namespace: rook-ceph
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: rook-csi-rbd-provisioner
    creationPolicy: Owner
  data:
    - secretKey: userID
      remoteRef:
        key: rook-ceph/rook-csi-rbd-provisioner
        property: userID
    - secretKey: userKey
      remoteRef:
        key: rook-ceph/rook-csi-rbd-provisioner
        property: userKey
