apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-config
  namespace: rook-ceph
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: rook-ceph-config
    creationPolicy: Merge
  data:
    - secretKey: mon_host
      remoteRef:
        key: rook-ceph/rook-ceph-config
        property: mon_host
    - secretKey: mon_initial_members
      remoteRef:
        key: rook-ceph/rook-ceph-config
        property: mon_initial_members
