apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-mon
  namespace: rook-ceph
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: rook-ceph-mon
    creationPolicy: Owner
  data:
    - secretKey: cluster-name
      remoteRef:
        key: rook-ceph/rook-ceph-mon
        property: cluster-name
    - secretKey: fsid
      remoteRef:
        key: rook-ceph/rook-ceph-mon
        property: fsid
    - secretKey: admin-secret
      remoteRef:
        key: rook-ceph/rook-ceph-mon
        property: admin-secret
    - secretKey: mon-secret
      remoteRef:
        key: rook-ceph/rook-ceph-mon
        property: mon-secret
    - secretKey: ceph-username
      remoteRef:
        key: rook-ceph/rook-ceph-mon
        property: ceph-username
    - secretKey: ceph-secret
      remoteRef:
        key: rook-ceph/rook-ceph-mon
        property: ceph-secret
