apiVersion: v1
kind: Service
metadata:
  name: openclaw-ui
  namespace: openclaw
  labels:
    app.kubernetes.io/name: openclaw
  annotations:
    external-dns.alpha.kubernetes.io/hostname: openclaw.internal.onoe.dev
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 18789
      name: https
  selector:
    app.kubernetes.io/name: openclaw
