apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obsidian-secrets
  namespace: obsidian
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: obsidian-secrets
  data:
    - secretKey: github-pat
      remoteRef:
        key: secret/obsidian/github-pat
        property: token
