installCRDs: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi

certController:
  enabled: false

webhook:
  certManager:
    enabled: true
    cert:
      issuerRef:
        name: internal-ca
        kind: ClusterIssuer
        group: cert-manager.io
