apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: alertmanager-slack-webhook
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: monitoring/alertmanager-slack-webhook
        property: url
