apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sshwifty-secrets
  namespace: sshwifty
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: sshwifty-secrets
  data:
    - secretKey: shared-key
      remoteRef:
        key: secret/sshwifty/shared-key
        property: value
    - secretKey: bastion-ssh-key
      remoteRef:
        key: secret/sshwifty/bastion-ssh-key
        property: private-key
