apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-root-token
  namespace: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: vault-root-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: vault/root-token
        property: token
