apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-unseal-keys
  namespace: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: vault-unseal-keys
    creationPolicy: Owner
  data:
    - secretKey: key-0
      remoteRef:
        key: vault/unseal-keys
        property: key-0
    - secretKey: key-1
      remoteRef:
        key: vault/unseal-keys
        property: key-1
