apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talosconfig
  namespace: node-reboot
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: talosconfig
    creationPolicy: Owner
  data:
    - secretKey: talosconfig
      remoteRef:
        key: node-reboot/talosconfig
        property: talosconfig
