cluster:
  network:
    cni:
      name: none
    podSubnets:
      - 10.3.0.0/16
    serviceSubnets:
      - 10.4.0.0/16
  proxy:
    disabled: true
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: off
