machine:
  install:
    disk: /dev/sda
---
apiVersion: v1alpha1
kind: LinkConfig
name: eth0
up: true
addresses:
  - address: 10.2.0.68/27
routes:
  - gateway: 10.2.0.65
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 10.2.0.94
link: eth0
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 10.0.0.1
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: k8s-cp-03
